[package]
authors = ['Setheum Labs<https://github.com/Setheum-Labs>']
description = 'serp-tes pallet template'
edition = '2018'
homepage = 'https://setheum.xyz'
license = 'Apache-2.0 License'
name = 'serp-tes'
repository = 'https://github.com/Setheum-Labs/Setheum/'
version = '0.4.1'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
adapters = { default-features = false, package = 'storage-adapters', version = '0.4.1', git = 'https://github.com/Setheum-Labs/storage-adapters' }
fetch-price = { default-features = false, package = 'fetch-price', version = '0.4.1', git = 'https://github.com/Setheum-Labs/fetch-price' }
stp258 = { default-features = false, package = 'stp258', version = '0.4.1', git = 'https://github.com/Setheum-Labs/stp258' }
serp-market = { default-features = false, package = 'serp-market', version = '0.4.1', git = 'https://github.com/Setheum-Labs/serp-market' }
serde = { version = "1.0.123", optional = true }
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false }
sp-std = { default-features = false, optional = true, version = '3.0.0' }
frame-support = { default-features = false, version = '3.0.0' }
frame-system = { default-features = false, version = '3.0.0' }
num-rational = { default-features = false, version = '0.3.2' }
fixed = { default-features = false, version = '1.6.0' }

[dev-dependencies]
sp-core = '3.0.0'
sp-io = '3.0.0'
sp-runtime = { default-features = false, version = '3.0.0' }

[features]
default = ['std']
std = [
    "adapters/std",
    'codec/std',
    "fetch-price/std",
    "fixed/std",
    'frame-support/std',
    'frame-system/std',
    "num-rational/std",
	"stp258/std",
    "serp-market/std",
	"serde/std",
    "sp-runtime/std",
    "sp-std/std",
]
