[package]
authors = ['Setheum Labs<https://github.com/Setheum-Labs>']
description = 'serp-tes pallet template'
edition = '2018'
homepage = 'https://setheum.xyz'
license = 'Apache-2.0 License'
name = 'serp-tes'
repository = 'https://github.com/Setheum-Labs/Setheum/'
version = '0.5.0-dev'

[dependencies]
serde = { version = "1.0.123", optional = true }
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false }
sp-std = { default-features = false, optional = true, version = '3.0.0' }
frame-support = { default-features = false, version = '3.0.0' }
frame-system = { default-features = false, version = '3.0.0' }
stp258 = { package = 'stp258', version = '0.5.4-dev', default-features = false, git = 'https://github.com/Setheum-Labs/stp258' }
stp258-tokens = { package = 'stp258-tokens', version = '0.5.0-dev', default-features = false, git = 'https://github.com/Setheum-Labs/stp258-tokens' }
serp-traits = { package = 'serp-traits', version = '0.5.0-dev', git = "https://github.com/Setheum-Labs/serp-traits"}

funty = { version = "1.1.0", default-features = false } # https://github.com/bitvecto-rs/bitvec/issues/105

num-rational = { default-features = false, version = '0.3.2' }
num-traits = { version = "0.2.14", default-features = false }
fixed = { default-features = false, version = '1.6.0' }

[dev-dependencies]
sp-core = '3.0.0'
sp-io = '3.0.0'
sp-runtime = { default-features = false, version = '3.0.0' }

[features]
default = ['std']
std = [
    'codec/std',
    'frame-support/std',
    'frame-system/std',
	"stp258/std",
	"stp258-tokens/std",
    "serp-traits/stp",
	"serde/std",
    "sp-runtime/std",
    "sp-std/std",
    "fixed/std",
    "num-rational/std",
	"num-traits/std",
]
